### ISSUE TITLE
Error: The argument type 'BorderRadiusGeometry?' can't be assigned to the parameter type 'BorderRadius?'

### ISSUE THREAD

**Issue by omer73364** [SaltyAom/niku#32]
I got this error after installing Niku and running the application for Linux

My OS: Linux PopOS 22
Flutter 3.3.8
Tools Dart 2.18.4
DevTools 2.15.0

![Screenshot from 2022-11-25 02-16-04](https://user-images.githubusercontent.com/61283834/203873643-36245cee-166d-4fb5-9c01-766a0a17482f.png)

**Comment by SaltyAom** [comment]
Assume that you're using Flutter 3.3+, updating Niku to 2.3.3 should solve the problem.
```yaml
# pubspec.yaml
dependencies: 
    flutter: 
        sdk: flutter 
    
    niku: 2.3.3 # Update here to 2.3.3
```

Let me know if this help~.
