### ISSUE TITLE
TextFormField Error

### ISSUE THREAD

**Issue by victor7w7r** [SaltyAom/niku#35]
Please help, when i compile the app shows me a error, i use Flutter 3.16.0

`hosted/pub.dev/niku-2.4.2/lib/widget/textFormField.dart:877:18: Error: The argument type 'bool?' can't be assigned to the parameter type 'bool' because 'bool?' is nullable and 'bool' isn't.
        enabled: enabled`

Thanks.

**Comment by dorklein** [comment]
Same for me, just started to happen when I upgraded Flutter to 3.16.0

**Comment by AkaraChen** [comment]
Same here

**Comment by ollyde** [comment]
I have the same issue does anyone have a quick fix?

**Comment by ollyde** [comment]
Temporary fix here

```
  niku:
    git:
      url: https://github.com/ollyde/niku
      ref: main
      resolved-ref: "9a4e534c211bad9130456b3018b9bcbd0941b9bf"
```

Creating pull request
